import AppKit
import Combine
import Foundation

/// Monitors the macOS system pasteboard, creates categorized history items,
/// enforces retention/privacy policies, and allows copying items back to the pasteboard.
@MainActor
public final class ClipboardManager: ObservableObject {
    @Published public private(set) var items: [ClipboardItem] = []
    @Published public var isPaused: Bool = false
    @Published public var filterSensitiveData: Bool = true
    @Published public var retentionLimit: RetentionLimit = .hundred
    @Published public var autoDeletePeriod: AutoDeletePeriod = .never

    private let pasteboard = NSPasteboard.general
    private let store: ClipboardStore
    private var lastChangeCount: Int = 0
    private var timer: Timer?

    public init(store: ClipboardStore = ClipboardStore()) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
        self.items = store.loadHistory(autoDeletePeriod: autoDeletePeriod)
        startMonitoring()
    }

    deinit {
        timer?.invalidate()
    }

    public func startMonitoring() {
        stopMonitoring()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkForChanges()
            }
        }
    }

    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    /// Checks if the pasteboard changeCount changed, and processes new entries.
    public func checkForChanges() {
        guard !isPaused else { return }

        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        // Check for password manager transient types (e.g. 1Password, Bitwarden, Keychain)
        if let types = pasteboard.types {
            let transientTypeNames = [
                "org.nspasteboard.TransientType",
                "org.nspasteboard.AutoGeneratedType",
                "org.nspasteboard.ConcealedType",
                "com.agilebits.onepassword"
            ]
            for transient in transientTypeNames {
                if types.contains(where: { $0.rawValue.contains(transient) }) {
                    return // Ignore password manager transient copies
                }
            }
        }

        // Process images first
        if let image = NSImage(pasteboard: pasteboard),
           let tiffData = image.tiffRepresentation,
           let bitmap = NSBitmapImageRep(data: tiffData),
           let pngData = bitmap.representation(using: .png, properties: [:]) {
            let id = UUID()
            let imagePath = store.saveImage(data: pngData, id: id)
            let item = ClipboardItem(
                id: id,
                timestamp: Date(),
                type: .image,
                preview: "Image (\(Int(image.size.width)) × \(Int(image.size.height)))",
                imagePath: imagePath
            )
            add(item: item)
            return
        }

        // Process file URLs
        if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            NSPasteboard.ReadingOptionKey.urlReadingFileURLsOnly: true
        ]) as? [URL], let firstURL = fileURLs.first {
            let filename = firstURL.lastPathComponent
            let item = ClipboardItem(
                id: UUID(),
                timestamp: Date(),
                type: .file,
                preview: filename,
                fileURLString: firstURL.absoluteString
            )
            add(item: item)
            return
        }

        // Process string content
        guard let string = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !string.isEmpty else {
            return
        }

        // Sensitive data heuristic check
        let isSensitive = detectSensitiveContent(string)
        if isSensitive && filterSensitiveData {
            return // Skip sensitive credentials if filtering is enabled
        }

        let contentType = classify(string: string)
        let preview = makePreview(for: string, type: contentType)

        let item = ClipboardItem(
            id: UUID(),
            timestamp: Date(),
            type: contentType,
            preview: preview,
            textContent: string,
            isSensitive: isSensitive,
            characterCount: string.count
        )

        add(item: item)
    }

    /// Adds a new item to history while preventing consecutive duplicates.
    public func add(item: ClipboardItem) {
        // Prevent consecutive duplicates
        if let first = items.first {
            if first.type == item.type {
                if let text1 = first.textContent, let text2 = item.textContent, text1 == text2 {
                    return
                }
                if let file1 = first.fileURLString, let file2 = item.fileURLString, file1 == file2 {
                    return
                }
            }
        }

        items.insert(item, at: 0)

        // Enforce limit
        if retentionLimit != .unlimited && items.count > retentionLimit.rawValue {
            items = Array(items.prefix(retentionLimit.rawValue))
        }

        store.saveHistory(items, limit: retentionLimit)
    }

    /// Copies a clipboard item back to the macOS pasteboard.
    public func copyToPasteboard(_ item: ClipboardItem) {
        pasteboard.clearContents()

        switch item.type {
        case .image:
            if let path = item.imagePath, let image = store.loadImage(filename: path) {
                pasteboard.writeObjects([image])
            }
        case .file:
            if let fileStr = item.fileURLString, let url = URL(string: fileStr) {
                pasteboard.writeObjects([url as NSURL])
            }
        case .text, .url, .code:
            if let text = item.textContent {
                pasteboard.setString(text, forType: .string)
            }
        }

        // Update change count so our own write doesn't get re-imported
        lastChangeCount = pasteboard.changeCount
    }

    /// Removes a specific item from history.
    public func remove(item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        store.saveHistory(items, limit: retentionLimit)
    }

    /// Clears the entire clipboard history.
    public func clearHistory() {
        items.removeAll()
        store.clearAll()
    }

    // MARK: - Classification & Heuristics

    public func classify(string: String) -> ClipboardContentType {
        if let url = URL(string: string), url.scheme != nil, ["http", "https", "ftp"].contains(url.scheme?.lowercased()) {
            return .url
        }

        if isLikelyCode(string) {
            return .code
        }

        return .text
    }

    private func isLikelyCode(_ string: String) -> Bool {
        let codeIndicators = [
            "func ", "import ", "const ", "let ", "var ", "class ", "struct ",
            "enum ", "def ", "return ", "public ", "private ", "interface ",
            "void ", "System.out", "console.log", "<div>", "<html", "SELECT ",
            "FROM ", "WHERE ", "async ", "await ", "namespace ", "=>", "{\n",
            ";\n"
        ]

        var matchCount = 0
        for indicator in codeIndicators {
            if string.contains(indicator) {
                matchCount += 1
                if matchCount >= 2 { return true }
            }
        }

        // Check for indentation or braces formatting
        if string.contains("{\n") || string.contains("    ") || string.contains("\t") {
            if string.count > 20 && (string.contains("(") && string.contains(")")) {
                return true
            }
        }

        return false
    }

    public func detectSensitiveContent(_ string: String) -> Bool {
        let lower = string.lowercased()
        if lower.hasPrefix("sk-") || lower.hasPrefix("ghp_") || lower.hasPrefix("glpat-") {
            return true
        }
        if string.contains("-----BEGIN") && string.contains("PRIVATE KEY-----") {
            return true
        }
        if lower.contains("bearer ") || lower.contains("authorization: ") {
            return true
        }
        return false
    }

    private func makePreview(for string: String, type: ClipboardContentType) -> String {
        let lines = string.components(separatedBy: .newlines).filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty }
        let singleLine = lines.prefix(2).joined(separator: " ").trimmingCharacters(in: .whitespaces)

        if singleLine.count > 120 {
            return String(singleLine.prefix(120)) + "…"
        }
        return singleLine
    }
}
