import AppKit
import Combine
import Foundation

/// Monitors the macOS system pasteboard, manages categorized history,
/// enforces search/filtering/pinning, and coordinates persistence.
@MainActor
public final class ClipboardManager: ObservableObject {
    @Published public private(set) var items: [ClipboardItem] = []
    @Published public var selectedCategory: ClipboardCategory = .all
    @Published public var searchQuery: String = ""
    @Published public var isPaused: Bool = false
    @Published public var filterSensitiveData: Bool = true
    @Published public var retentionLimit: RetentionLimit = .hundred
    @Published public var autoDeletePeriod: AutoDeletePeriod = .never
    @Published public var duplicatePolicy: ClipboardDuplicatePolicy = .moveToTop

    private let pasteboard = NSPasteboard.general
    private let store: ClipboardStore
    private let searchEngine = ClipboardSearchEngine.shared
    private let previewProvider = ClipboardPreviewProvider.shared
    private var lastChangeCount: Int = 0
    private var timer: Timer?

    public init(store: ClipboardStore = ClipboardStore()) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
        self.items = store.loadHistory(autoDeletePeriod: autoDeletePeriod)
        startMonitoring()
    }

    deinit {
        timer?.invalidate()
    }

    public func startMonitoring() {
        stopMonitoring()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkForChanges()
            }
        }
    }

    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    /// Filtered and sorted items according to the active category and search query.
    public var filteredItems: [ClipboardItem] {
        searchEngine.search(items: items, category: selectedCategory, query: searchQuery)
    }

    // MARK: - Change Detection

    public func checkForChanges() {
        guard !isPaused else { return }

        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        // 1. Password manager transient types (1Password, Bitwarden, Keychain)
        if let types = pasteboard.types {
            let transientTypeNames = [
                "org.nspasteboard.TransientType",
                "org.nspasteboard.AutoGeneratedType",
                "org.nspasteboard.ConcealedType",
                "com.agilebits.onepassword"
            ]
            for transient in transientTypeNames {
                if types.contains(where: { $0.rawValue.contains(transient) }) {
                    return
                }
            }
        }

        // 2. Process images
        if let image = NSImage(pasteboard: pasteboard),
           let tiffData = image.tiffRepresentation,
           let bitmap = NSBitmapImageRep(data: tiffData),
           let pngData = bitmap.representation(using: .png, properties: [:]) {
            let id = UUID()
            let imagePath = store.saveImage(data: pngData, id: id)
            let dims = CGSize(width: image.size.width, height: image.size.height)
            let item = ClipboardItem(
                id: id,
                timestamp: Date(),
                type: .image,
                preview: "Image (\(Int(dims.width)) × \(Int(dims.height)))",
                imagePath: imagePath,
                imageDimensions: dims
            )
            add(item: item)
            return
        }

        // 3. Process file URLs
        if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            NSPasteboard.ReadingOptionKey.urlReadingFileURLsOnly: true
        ]) as? [URL], let firstURL = fileURLs.first {
            let filename = firstURL.lastPathComponent
            var fileSize: Int64?
            if let attrs = try? FileManager.default.attributesOfItem(atPath: firstURL.path),
               let size = attrs[.size] as? Int64 {
                fileSize = size
            }

            let preview = filename
            let item = ClipboardItem(
                id: UUID(),
                timestamp: Date(),
                type: .file,
                preview: preview,
                fileURLString: firstURL.absoluteString,
                fileSize: fileSize
            )
            add(item: item)
            return
        }

        // 4. Process string content
        guard let string = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !string.isEmpty else {
            return
        }

        let isSensitive = detectSensitiveContent(string)
        if isSensitive && filterSensitiveData {
            return
        }

        let contentType = classify(string: string)
        let preview = previewProvider.generatePreview(for: string, type: contentType)

        let item = ClipboardItem(
            id: UUID(),
            timestamp: Date(),
            type: contentType,
            preview: preview,
            textContent: string,
            isSensitive: isSensitive,
            characterCount: string.count
        )

        add(item: item)
    }

    // MARK: - Item Management & Deduplication

    public func add(item: ClipboardItem) {
        // Consecutive duplicate check
        if let first = items.first, isContentEqual(first, item) {
            return
        }

        // Non-consecutive duplicate check based on policy
        if duplicatePolicy == .moveToTop {
            if let existingIndex = items.firstIndex(where: { isContentEqual($0, item) }) {
                let existing = items.remove(at: existingIndex)
                let updated = ClipboardItem(
                    id: existing.id,
                    timestamp: Date(),
                    type: existing.type,
                    preview: existing.preview,
                    textContent: existing.textContent,
                    imagePath: existing.imagePath,
                    fileURLString: existing.fileURLString,
                    isSensitive: existing.isSensitive,
                    characterCount: existing.characterCount,
                    isPinned: existing.isPinned,
                    fileSize: existing.fileSize,
                    imageDimensions: existing.imageDimensions
                )
                insertSorted(item: updated)
                store.saveHistory(items, limit: retentionLimit)
                return
            }
        }

        insertSorted(item: item)

        // Enforce retention limit (pinned items protected)
        if retentionLimit != .unlimited {
            let maxTotal = retentionLimit.rawValue
            let pinned = items.filter { $0.isPinned }
            let unpinned = items.filter { !$0.isPinned }
            let remainingSlots = max(0, maxTotal - pinned.count)
            items = pinned + Array(unpinned.prefix(remainingSlots))
        }

        store.saveHistory(items, limit: retentionLimit)
    }

    private func insertSorted(item: ClipboardItem) {
        if item.isPinned {
            // Pinned items stay at the very top
            items.insert(item, at: 0)
        } else {
            // Place after existing pinned items
            let firstUnpinnedIndex = items.firstIndex(where: { !$0.isPinned }) ?? items.count
            items.insert(item, at: firstUnpinnedIndex)
        }
    }

    private func isContentEqual(_ a: ClipboardItem, _ b: ClipboardItem) -> Bool {
        guard a.type == b.type else { return false }
        if let t1 = a.textContent, let t2 = b.textContent {
            return t1 == t2
        }
        if let f1 = a.fileURLString, let f2 = b.fileURLString {
            return f1 == f2
        }
        if let i1 = a.imagePath, let i2 = b.imagePath {
            return i1 == i2
        }
        return false
    }

    // MARK: - Pinning Actions

    public func togglePin(item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        var updated = items.remove(at: index)
        updated.isPinned.toggle()

        insertSorted(item: updated)
        store.saveHistory(items, limit: retentionLimit)
    }

    public func pin(item: ClipboardItem) {
        if !item.isPinned {
            togglePin(item: item)
        }
    }

    public func unpin(item: ClipboardItem) {
        if item.isPinned {
            togglePin(item: item)
        }
    }

    // MARK: - Pasteboard Write

    public func copyToPasteboard(_ item: ClipboardItem) {
        pasteboard.clearContents()

        switch item.type {
        case .image:
            if let path = item.imagePath, let image = store.loadImage(filename: path) {
                pasteboard.writeObjects([image])
            }
        case .file:
            if let fileStr = item.fileURLString, let url = URL(string: fileStr) {
                pasteboard.writeObjects([url as NSURL])
            }
        case .text, .url, .code:
            if let text = item.textContent {
                pasteboard.setString(text, forType: .string)
            }
        }

        lastChangeCount = pasteboard.changeCount
    }

    public func copyPlainTextToPasteboard(_ item: ClipboardItem) {
        if let text = item.textContent ?? item.fileURLString {
            pasteboard.clearContents()
            pasteboard.setString(text, forType: .string)
            lastChangeCount = pasteboard.changeCount
        }
    }

    // MARK: - Deletion

    public func remove(item: ClipboardItem) {
        if let path = item.imagePath {
            store.deleteImage(filename: path)
        }
        items.removeAll { $0.id == item.id }
        store.saveHistory(items, limit: retentionLimit)
    }

    public func clearHistory() {
        // Clear unpinned items only, or all if none pinned
        items.removeAll { !$0.isPinned }
        store.saveHistory(items, limit: retentionLimit)
        store.cleanOrphanedImages(activeItems: items)
    }

    public func clearAllIncludingPinned() {
        items.removeAll()
        store.clearAll()
    }

    // MARK: - Classification & Heuristics

    public func classify(string: String) -> ClipboardContentType {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        if let url = URL(string: trimmed), url.scheme != nil, ["http", "https", "ftp"].contains(url.scheme?.lowercased()) {
            return .url
        }

        if isLikelyCode(trimmed) {
            return .code
        }

        return .text
    }

    public func isLikelyCode(_ string: String) -> Bool {
        let codeIndicators = [
            "func ", "import ", "const ", "let ", "var ", "class ", "struct ",
            "enum ", "def ", "return ", "public ", "private ", "interface ",
            "void ", "System.out", "console.log", "<div>", "<html", "SELECT ",
            "FROM ", "WHERE ", "async ", "await ", "namespace ", "=>", "{\n",
            ";\n"
        ]

        var matchCount = 0
        for indicator in codeIndicators {
            if string.contains(indicator) {
                matchCount += 1
                if matchCount >= 2 { return true }
            }
        }

        if (string.contains("{\n") || string.contains("    ") || string.contains("\t")) &&
            string.count > 20 && string.contains("(") && string.contains(")") {
            return true
        }

        return false
    }

    /// Robust sensitive credential detection avoiding false positives on ordinary source code.
    public func detectSensitiveContent(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)

        // API Keys and Tokens
        if trimmed.hasPrefix("sk-proj-") || trimmed.hasPrefix("sk-ant-") ||
           trimmed.hasPrefix("ghp_") || trimmed.hasPrefix("gho_") ||
           trimmed.hasPrefix("glpat-") {
            return true
        }

        // Private Keys
        if trimmed.contains("-----BEGIN") && trimmed.contains("PRIVATE KEY-----") {
            return true
        }

        // Long Bearer tokens (must have actual base64/hex token of length >= 20)
        let lower = trimmed.lowercased()
        if lower.hasPrefix("bearer ") && trimmed.count >= 28 {
            return true
        }

        return false
    }
}
